name: nextcloud-client-kyrofa
version: 2.2.4
summary: Nextcloud Desktop Client
grade: stable
confinement: strict
description: |
  The Nextcloud Desktop Client is a tool to synchronize files from a Nextcloud
  Server with your local computer.

apps:
  nextcloud-client:
    command: env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/lib/nextcloud desktop-launch nextcloud
    plugs:
      - network
      - network-bind
      - unity7
      - home

parts:
  client:
    plugin: cmake
    source: https://github.com/nextcloud/client_theming.git
    source-tag: v2.2.4
    source-subdir: client
    configflags:
      - -DOEM_THEME_DIR=$SNAPCRAFT_PART_INSTALL/../src/nextcloudtheme
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DSYSCONF_INSTALL_DIR=config
    build-packages:
      - g++
      - sed
      - libsqlite3-dev
      - python3-sphinx
      - libssl-dev
      - libqt5webkit5-dev
      - qt5keychain-dev
    after: [desktop-qt5]
